import type {
  LanDeviceDefinition,
  QuickLink,
} from "@/features/dashboard/types";

export const dashboardCatalog = {
  networkLinkLabel: "2.5G",
  devices: [
    {
      id: "k3s-control",
      name: "k3s-control",
      address: "192.168.10.21",
      url: "https://192.168.10.21",
      kind: "vm",
      provider: { type: "proxmox", id: "101" },
    },
    {
      id: "k3s-worker-01",
      name: "k3s-worker-01",
      address: "192.168.10.22",
      url: "https://192.168.10.22",
      kind: "vm",
      provider: { type: "proxmox", id: "102" },
    },
    {
      id: "k3s-worker-02",
      name: "k3s-worker-02",
      address: "192.168.10.23",
      url: "https://192.168.10.23",
      kind: "vm",
      provider: { type: "proxmox", id: "103" },
    },
    {
      id: "reverse-proxy",
      name: "reverse-proxy",
      address: "192.168.10.30",
      url: "https://192.168.10.30",
      kind: "container",
      provider: { type: "proxmox", id: "110" },
    },
    {
      id: "database",
      name: "database",
      address: "192.168.10.31",
      url: "https://192.168.10.31",
      kind: "vm",
      provider: { type: "proxmox", id: "111" },
    },
    {
      id: "monitoring",
      name: "monitoring",
      address: "192.168.10.32",
      url: "https://192.168.10.32",
      kind: "container",
      provider: { type: "proxmox", id: "112" },
    },
    {
      id: "home-automation",
      name: "home-automation",
      address: "192.168.10.40",
      url: "https://192.168.10.40",
      kind: "vm",
      provider: { type: "proxmox", id: "120" },
    },
    {
      id: "dns-primary",
      name: "dns-primary",
      address: "192.168.10.53",
      url: "https://192.168.10.53",
      kind: "container",
      provider: { type: "proxmox", id: "153" },
    },
  ] satisfies LanDeviceDefinition[],
  links: [
    {
      id: "grafana",
      name: "Grafana",
      url: "https://grafana.local",
      glyph: "GF",
    },
    {
      id: "adguard",
      name: "AdGuard",
      url: "https://adguard.local",
      glyph: "AG",
    },
    {
      id: "home-assistant",
      name: "Home Assistant",
      url: "https://home.local",
      glyph: "HA",
    },
    {
      id: "portainer",
      name: "Portainer",
      url: "https://portainer.local",
      glyph: "PT",
    },
    { id: "git", name: "Git", url: "https://git.local", glyph: "GT" },
    {
      id: "uptime-kuma",
      name: "Uptime Kuma",
      url: "https://uptime.local",
      glyph: "UK",
    },
    { id: "vault", name: "Vault", url: "https://vault.local", glyph: "VB" },
    { id: "files", name: "Files", url: "https://files.local", glyph: "FS" },
    { id: "router", name: "Router", url: "https://router.local", glyph: "RT" },
    {
      id: "cloudflare",
      name: "Cloudflare",
      url: "https://dash.cloudflare.com",
      glyph: "CF",
    },
  ] satisfies QuickLink[],
} as const;
